
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]] #mandatory
modId="tinkers_wizardry"
version="0.0.1"
displayName="Tinkers' Wizardry"
logoFile="examplemod.png"
credits="Me."
authors="SnackPirate"
description='''
Adds various magic-related things to Tinkers' Construct.
'''
[[dependencies.tinkerswizardry]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkerswizardry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkersexpansion]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.6.3.111,)"
    ordering="NONE"
    side="BOTH"